name: adescrow_app
description: Escroc App

publish_to: 'none'

version: 1.2.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  # manually added dependency
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  google_fonts: 6.2.1
  country_code_picker: ^3.0.0
  get_storage: ^2.1.1
  logger: 2.1.0
  pin_code_fields: ^8.0.1
  intl: 0.19.0
  http: 1.2.1
  path_provider: 2.1.2
  path: ^1.8.3
  mime: 1.0.5
  image_picker: 1.0.7
  file_picker: 6.2.0
  flutter_svg: 2.0.10+1
  flutter_spinkit: ^5.2.0
  cached_network_image: 3.3.1
  dotted_decoration: ^2.0.0
  flutter_inappwebview: 6.0.0
  flutter_animate: 4.5.0
  connectivity_plus: 5.0.2
  flutter_pdfview: ^1.3.2
  local_auth: 2.2.0

  permission_handler:
  device_info_plus: 9.1.2
  dropdown_button2:
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.1
  flutter_launcher_icons: 0.13.1
#  flutter_app_name: ^0.1.1
  change_app_package_name: ^1.1.0
  build_runner:
  flutter_gen_runner:


flutter_app_name:
  name: "JaAme"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_launcher.jpg"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
#  flutter packages pub run build_runner build
#  fluttergen -c pubspec.yaml  # only for mac

# ------------------- or ----------------
#  flutter pub run flutter_app_name
# flutter pub run flutter_launcher_icons:main
# flutter pub run change_app_package_name:main com.domain.appname  // net.appdevs.escroc // net.appdevs.escroc

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/logo/app_launcher.jpg
    - assets/logo/ios_launcher.jpg
    - assets/placeholder/